---
hero_image: images / banner.png
theme: blå
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programmering-0, phys-comp-0, produksjon-0, fellesskap-0
title: Oppskrift
description: Lag en nettside av favorittoppskriften din, slik at vennene dine kan gjøre det!
original_url: https://codeclubprojects.org/en-GB/webdev/recipe
interests: ''
technologies: html-css-javascript
site_areas: prosjekter
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduksjon
  - 
    title: Bestem deg på en oppskrift
  - 
    title: ingredienser
  - 
    title: 'Utfordring: Flere ingredienser'
  - 
    title: Metode
  - 
    title: 'Utfordring: Flere skritt'
  - 
    title: Farger!
  - 
    title: Finpuss
  - 
    title: 'Utfordring: Flere farger!'
  - 
    title: 'Utfordring: Anmeldelser'
  - 
    title: 'Utfordring: Mer styling'
