---
hero_image: images/banner.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Receita
description: Cria uma página web com a tua receita favorita, para que os teus amigos a possam fazer!
original_url: https://codeclubprojects.org/en-GB/webdev/recipe
interests: ''
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introdução
  - 
    title: Escolhe uma receita
  - 
    title: Ingredientes
  - 
    title: 'Desafio: Mais ingredientes'
  - 
    title: Preparaçāo
  - 
    title: 'Desafio: Mais passos'
  - 
    title: Cores!
  - 
    title: Retoques finais
  - 
    title: 'Desafio: Mais cores!'
  - 
    title: 'Desafio: Comentários'
  - 
    title: 'Desafio: Mais stilo'
