---
hero_image: images/recipe.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Receta
description: ¡Crea una página web con tu receta favorita para que tus amigos puedan prepararla!
original_url: https://codeclubprojects.org/en-GB/webdev/recipe
interests: ''
technologies: html/css
site_areas: codeclub, webdev
steps:
- title: Introducción
- title: Decide que receta quieres hacer
- title: Ingredientes
- title: 'Desafío: Más ingredientes'
- title: Preparación
- title: 'Desafío: Más pasos'
- title: ¡Colores!
- title: Toques finales
- title: 'Desafío: ¡Más colores!'
- title: 'Desafío: Revisiones'
- title: 'Desafío: Más estilos'

