---
hero_image: images/recipe.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Recipe
description: Erstelle eine Webseite mit deinem Lieblingsrezept, damit deine Freunde es nachmachen können!
original_url: https://codeclubprojects.org/en-GB/webdev/recipe
interests: ''
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps: 
- title: Einführung
- title: Wähle ein Rezept aus
- title: Zutaten
- title: 'Aufgabe: Noch mehr Zutaten'
- title: Methode
- title: 'Aufgabe: Weitere Schritte'
- title: Farben!
- title: Der letzte Schliff
- title: 'Aufgabe: Noch mehr Farben!'
- title: 'Aufgabe: Beurteilungen'
- title: 'Aufgabe: Noch mehr Gestaltungsmöglichkeiten'