---
hero_image: images/banner.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Rezept
description: Erstelle eine Webseite mit deinem Lieblingsrezept, damit deine Freunde
  es nachmachen können!
original_url: https://codeclubprojects.org/en-GB/webdev/recipe
interests: ''
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
- title: Einleitung
- title: Wähle ein Rezept aus
- title: Zutaten
  completion:
  - engaged
- title: 'Aufgabe: Noch mehr Zutaten'
- title: Zubereitung
- title: 'Aufgabe: Weitere Schritte'
- title: Farben!
- title: Der letzte Schliff
  completion:
  - internal
- title: 'Aufgabe: Noch mehr Farben!'
- title: 'Aufgabe: Beurteilungen'
- title: 'Aufgabe: Noch mehr Gestaltungsmöglichkeiten'
