---
hero_image: images/banner.png
theme: albastru
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Recipe
description: Create a webpage of your favourite recipe, so that your friends can make it!
original_url: https://codeclubprojects.org/en-GB/webdev/recipe
interests: ''
technologies: html-css-JavaScript
site_areas: proiecte
hardware: ''
software: html-css-JavaScript
version: 3
last_tested: 01-01-2017
steps:
  - 
    title: Introducere
  - 
    title: Decide on a recipe
  - 
    title: Ingredients
  - 
    title: 'Challenge: More ingredients'
  - 
    title: Method
  - 
    title: 'Challenge: More steps'
  - 
    title: Colours!
  - 
    title: Finishing touches
  - 
    title: 'Challenge: More colours!'
  - 
    title: 'Challenge: Reviews'
  - 
    title: 'Challenge: More styling'
