---
hero_image: images/banner.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: A receita
description: Neste projeto você aprenderá a criar uma página de internet para sua receita favorita.
original_url: https://codeclubprojects.org/en-GB/webdev/recipe
interests: ''
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 01/01/2017
steps:
  - 
    title: Receita
  - 
    title: Escolha uma receita
  - 
    title: Ingredientes
  - 
    title: 'Desafio: Mais ingredientes'
  - 
    title: Modo de preparo
  - 
    title: 'Desafio: Mais passos'
  - 
    title: Cores!
  - 
    title: Toques finais
  - 
    title: 'Desafio: Mais cores!'
  - 
    title: 'Desafio: Revisão'
  - 
    title: 'Desafio: Mais estilos'
