---
hero_image: images/banner.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Recept
description: Készíts egy weboldalt a kedvenc receptedről, hogy a barátaid is el tudják készíteni!
original_url: https://codeclubprojects.org/en-GB/webdev/recipe
interests: ''
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Bevezetés
  - 
    title: Válassz egy receptet
  - 
    title: Hozzávalók
    completion:
      - engaged
  - 
    title: 'Kihívás: Több hozzávaló'
  - 
    title: Elkészítés
  - 
    title: 'Kihívás: Több lépés'
  - 
    title: Színek!
  - 
    title: Utolsó simítások
    completion:
      - internal
  - 
    title: 'Kihívás: Több szín!'
  - 
    title: 'Kihívás: Vélemények'
  - 
    title: 'Kihívás: Több stílus'
