---
hero_image: images/banner.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Retsept
description: Loo oma lemmikretseptist veebileht, et su sõbrad saaksid seda valmistada!
original_url: https://codeclubprojects.org/en-GB/webdev/recipe
interests: ''
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
- title: Sissejuhatus
  completion: engaged
- title: Vali retsept
- title: Koostisosad
- title: 'Väljakutse: rohkem koostisosi'
- title: Valmistamine
- title: 'Väljakutse: veel samme'
- title: Värvid!
- title: Viimistlus
- title: 'Väljakutse: rohkem värve!'
- title: 'Väljakutse: arvustused'
  completion: internal
- title: 'Väljakutse: rohkem laade'
