---
hero_image: images / banner.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Przepis
description: Naucz się, jak stworzyć stronę internetową ze swoim ulubionym przepisem, aby twoi znajomi mogli go zrobić!
original_url: https://codeclubprojects.org/en-GB/webdev/recipe
interests: ''
technologies: html-css-javascript
site_areas: projekty
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Wprowadzenie
  - 
    title: Zdecyduj się na przepis
  - 
    title: Ingredients
  - 
    title: 'Challenge: More ingredients'
  - 
    title: Method
  - 
    title: 'Challenge: More steps'
  - 
    title: Colours!
  - 
    title: Finishing touches
  - 
    title: 'Wyzwanie: Więcej kolorów!'
  - 
    title: 'Challenge: Reviews'
  - 
    title: 'Challenge: More styling'
