---
hero_image: images / banner.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Przepis
description: Naucz się, jak stworzyć stronę internetową ze swoim ulubionym przepisem, aby twoi znajomi mogli go zrobić!
original_url: https://codeclubprojects.org/en-GB/webdev/recipe
interests: ''
technologies: html-css-javascript
site_areas: projekty
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Wprowadzenie
  - 
    title: Zdecyduj się na przepis
  - 
    title: Składniki
  - 
    title: 'Wyzwanie: więcej składników'
  - 
    title: Sposób wykonania
  - 
    title: 'Wyzwanie: Więcej kroków'
  - 
    title: Kolory!
  - 
    title: Ostatnie pociągnięcia
  - 
    title: 'Wyzwanie: Więcej kolorów!'
  - 
    title: 'Wyzwanie: Recenzje'
  - 
    title: 'Wyzwanie: Więcej kolorów'
