---
hero_image: images/banner.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Recept
description: Napravi veb-stranicu svog omiljenog recepta, kako bi tvoji prijatelji mogli da ga isprobaju!
original_url: https://codeclubprojects.org/en-GB/webdev/recipe
interests: ''
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Uvod
  - 
    title: Odaberi recept
  - 
    title: Sastojci
  - 
    title: 'Izazov: Više sastojaka'
  - 
    title: Priprema
  - 
    title: 'Izazov: Više koraka'
  - 
    title: Boje!
  - 
    title: Završni detalji
  - 
    title: 'Izazov: Više boja!'
  - 
    title: 'Izazov: Komentari'
  - 
    title: 'Izazov: Više stilova'
