---
hero_image: images/banner.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programmation-0, phys-comp-0, fabrication-0, communauté-0
title: Recette
description: Crée une page web pour ta recette préférée, afin que tes amis puissent la suivre !
original_url: https://codeclubprojects.org/en-GB/webdev/recipe
interests: ''
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 01/01/2017
steps:
  - 
    title: Introduction
  - 
    title: Choisis ta recette
  - 
    title: Ingrédients
  - 
    title: 'Défi : Ajouter plus d''ingrédients'
  - 
    title: Méthode
  - 
    title: 'Défi : Ajouter des étapes'
  - 
    title: Couleurs!
  - 
    title: Touches finales
  - 
    title: 'Défi : Plus de couleurs !'
  - 
    title: 'Défi: Commentaires'
  - 
    title: 'Défi: Plus de style'
