---
hero_image: images/recipe.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Recette de cuisine
description: Créer une page web au sujet de votre recette préférée, afin que vos amis puissent la suivre!
original_url: https://codeclubprojects.org/en-GB/webdev/recipe
interests: ''
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: Choisi ta recette
- title: Ingrédients
- title: "Défi: Plus d'ingrédients"
- title: Method
- title: "Défi: Plus d'étapes"
- title: Couleurs!
- title: Touches finales
- title: 'Défi: Plus de couleurs!'
- title: 'Défi: Commentaires'
- title: 'Défi: Plus de style'