---
hero_image: images/banner.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Ricetta
description: Crea una pagina web della tua ricetta preferita, in modo che i tuoi amici possano realizzarla!
original_url: https://codeclubprojects.org/en-GB/webdev/recipe
interests: ''
technologies: html-css-javascript
site_areas: progetti
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduzione
  - 
    title: Decidi una ricetta
  - 
    title: Ingredienti
  - 
    title: 'Sfida: Altri ingredienti'
  - 
    title: Metodo
  - 
    title: 'Sfida: Altri passi'
  - 
    title: Colori!
  - 
    title: Il tocco finale
  - 
    title: 'Sfida: Altri colori!'
  - 
    title: 'Sfida: Recensioni'
  - 
    title: 'Sfida: Più stile'
