---
hero_image: images/recipe.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Ricetta
description: Crea una pagina web della tua ricetta preferita, in modo che i tuoi amici possano realizzarla!
original_url: https://codeclubprojects.org/en-GB/webdev/recipe
interests: ''
technologies: html/css
site_areas: codeclub, webdev
steps:
- title: Introduzione
- title: Decidi una ricetta
- title: Ingredienti
- title: 'Sfida: Altri ingredienti'
- title: Metodo
- title: 'Sfida: Altri passi'
- title: Colori!
- title: Il tocco finale
- title: 'Sfida: Altri colori!'
- title: 'Sfida: Recensioni'
- title: 'Sfida: Più stile'

