---
hero_image: images/banner.png
theme: mavi
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, tasarım-1, programlama-0, fizik-hesaplama-0, üretim-0, topluluk-0
title: Yemek tarifi
description: Favori tarifinizin bir web sayfasını oluşturun, böylelikle arkadaşlarınız da bunu yapabilir!
original_url: https://codeclubprojects.org/en-GB/webdev/recipe
interests: ''
technologies: html-css-javascript
site_areas: projeler
hardware: ''
software: html-css-javascript
version: 3
last_tested: 01/01/2017
steps:
  - 
    title: Giriş
  - 
    title: Bir tarife karar verin
  - 
    title: Malzemeler
  - 
    title: 'Meydan okuma: Daha fazla malzeme'
  - 
    title: Yöntem
  - 
    title: 'Meydan Okuma: Daha fazla adım'
  - 
    title: Renkler!
  - 
    title: Son rötuşlar
  - 
    title: 'Meydan Okuma: Daha fazla renk!'
  - 
    title: 'Meydan Okuma: Yorumlar'
  - 
    title: 'Meydan Okuma: Daha fazla şekillendirme'
